---

- hosts: pospare
  gather_facts: yes
  become: yes
  tasks:
    - name: iptables allow http
      ansible.builtin.iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 80
        jump: ACCEPT
        action: insert
        rule_num: 5