---
k3s_version: v1.22.3+k3s1
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/oci_rsa
systemd_dir: /etc/systemd/system
master_ip: "{{ hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0]) }}"
extra_server_args: "--tls-san {{master_ip}}"
extra_agent_args: ""
